version: '3.1'
services:
  mongo:
    build: ./mongodb_rs
    restart: always
    volumes:
      - ./mongodb_rs/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: raceputin
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: mongo
      MONGO_REPLICA_HOST: localhost
      MONGO_REPLICA_PORT: 27017
    ports:
      - '27017:27017'